### ISSUE TITLE
BGHUDTableView should use BGHUDTextFieldCells?

### ISSUE THREAD

**Issue by rjo** [timthedevguy/BGHUDAppKit#12]
I have noticed that when editing a table cell the cursor color is black, making it pretty hard to see what one is editing.  Looking at the code, it seems that BGHUDTableView is using a default NSTextFieldCell rather than a BGHUDTextFieldCell, which would makethe cursor the same as the text color.  I've tried to implement this but when I set the table column cell to an instance of BGHUDTextFieldCell the fields become non-editable and I can't figure out why.

An example of my attempt to use the custom cell type is at http://pastebin.com/m23107dda

Anyone know whats up with that?

**Comment by rjo** [comment]
I'm a dork ... didn't consider setting the cell type in IB which works just fine.

**Comment by timthedevguy** [comment]
Just got off work, sorry for the long delay.  I didn't make it those the default cells because it wasn't really needed.  I just overrode the default handling of text based cells within BGHUDTableView so that it would display those cells colors based on the tableview's own themeKey.  I know I shouldn't assume that users would want this the same, but I'm a horrible person lol :)

But true, I will see if I can persuade the cursor to become the color we want in my default implementation :)

**Comment by rjo** [comment]
One thing I did notice in that if one happens to have a hud text field in a view, and edits it, that changes the insertion point color rather permanently such that all other text fields then get the new cursor color.  If that is ok, you could just get a reference to the shared field editor in the table view and change it there.  I still cant figure out why my method above didn't fly though

**Comment by timthedevguy** [comment]
Somehow I missed this last post, I'll look at that, I may need to cache the original color and set it back.

**Comment by timthedevguy** [comment]
Ok, so I figured a temporary solution, in this commit c025a450d189d7733a83, this is far from permanent as it is still kinda quirky, but will have to do until I can figure out how to use custom field editor.

**Comment by timthedevguy** [comment]
fixed

**Comment by rjo** [comment]
Awesome ... thanks for stickin with it BG!

**Comment by timthedevguy** [comment]
oops, this was supposed to be left open.  Sorry for the confusion, this is now I Known Issue
