### ISSUE TITLE
NSImage in BGHUDPopUpButtonCell

### ISSUE THREAD

**Issue by mahal** [timthedevguy/BGHUDAppKit#2]
Have you planned to draw the image of a Cell inside a BGHUDPopUpButtonCell?

**Comment by timthedevguy** [comment]
Good point, I'll get on it.

**Comment by timthedevguy** [comment]
Issue #2 - BGHUDPopupButtonCell Image

This update fixes issue #2, BGHUDPopUpButtonCell image drawing.  Currently only Left/Right/NoImage settings are supported.  Closed by b0f09f2a6b9e645e346a415b2f9154c0c91c2e79

**Comment by alinebee** [comment]
There's a bug in this implementation, whereby popup menu items will draw their images upside-down. This is because BGHUDPopUpButtonCell's -drawImage:withFrame:inView: is flipping the image to draw it (correctly) into the popup button, but leaving it flipped afterwards, so the menu item draws the flipped version.

This can be fixed by adding [image setFlipped: NO]; at the button of drawImage::withFrame:inView: after all drawing has been done. Of course, if more modifications would be made to the image in future versions, then a copy of the image should be made and modified instead.

**Comment by timthedevguy** [comment]
Ah, good catch!!!!

**Comment by timthedevguy** [comment]
Fixes BGHUDPopUpButtonCell image fliped'ness

Fixed the image fliped'ness. Thanks to alunbestor for catching this. Closed by 8a1d9bd0672e9c80c4764e03c8442e662e5bc5f1
