### ISSUE TITLE
Column Adding in BGHUDOutlineView

### ISSUE THREAD

**Issue by vsarpe** [timthedevguy/BGHUDAppKit#5]
Hi, Adding columns via Interface Builder for BGHUDOutlineView adds columns with plain headers (the silver ones found in normal NSOutlineView).

Since the default column numbers for the BGHUDOutlineView is 2, if I go to interface builder and increase the number of columns, it will add silver additional headers instead of black.

Am I missing something? Is there a way around it?

**Comment by timthedevguy** [comment]
Oops, good catch.  I'll add that to the que.

**Comment by benlowndes** [comment]
You can work around this by copying the existing columns in the Nib navigator. Just browse into the tableview columns and command-c to copy the column and command-v to paste the copies in.

**Comment by timthedevguy** [comment]
I've been digging for a way to fix this and I just realized that the only place you see the silver headers is IB, when you run the app it's fine.

Unfortunately this is an unavoidable quirk.  The silver header appears because BGHUDAppKit can't intercept the message and tell it to use a BGHUD style header during IB creation.  When the object is unarchived from disk (when you run your app) the substitution is made.
