### ISSUE TITLE
BGHUDTokenField Visual Issues in OSX Lion

### ISSUE THREAD

**Issue by erichoracek** [timthedevguy/BGHUDAppKit#59]
I've encountered some issues with the BGHUDTokenField class when both building (with XCode 4.1) and running in OSX Lion 10.7 (Developer Build 2). 

First off, the placeholder value in the BGHUDTokenField doesn't disappear when the cursor is in the text box:

On Lion:
http://dl.dropbox.com/u/3496930/TokenPalceholderLion.png

Snow Leopard:
http://dl.dropbox.com/u/3496930/TokenPlaceholderSnowLeopard.png

Second of all (I'm not sure if the BGHUDTokenField implementation has anything to do with this), the TokenField dropdown selection menu doesn't show the entirety of the items, only a limited amount truncated by an elipsis:

On Lion:
http://dl.dropbox.com/u/3496930/TokenMenuLion.png

On Snow Leopard:
http://dl.dropbox.com/u/3496930/TokenMenuSnowLeopard.png

(The blurring of contact information is by me, what's of note is that it's truncated far too early)

Thanks,
Eric

**Comment by timthedevguy** [comment]
Eric,

While I am not 100% sure, but I believe the ONLY approved way to talk about OS X Lion before release is in the Developer forums, I appreciate the information regardless but please don't post OS X Lion information here.  (I'd hate to loose my Developer account and or Github stuff because of it, yes I'm that paranoid)

I do have a Developer account and am currently working on updating BGHUDAppKit accordingly.

**Comment by erichoracek** [comment]
Apologies. You can delete this issue then. Just wanted to let you know.

**Comment by timthedevguy** [comment]
No problem Eric.  I'm currently trying to find out if we can converse via email about the issue since (and I'm assuming here) that we both have Developer accounts and are under the same NDA.

**Comment by erichoracek** [comment]
Sounds good. If we can't, we can move to a thread on the dev forums.
